version: '3'

services:
  app:
    build:
      context: node
    image: 1aquila1/nodeapp:dev
    container_name: app
    tty: true
    depends_on:
      - db
    networks:
      - node-network
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=aquila
    networks:
      - node-network

networks:
  node-network:
    driver: bridge